export const DEFAULT_GALLERY_IMAGE = '/img/logo.jpg';

export function generateGalleryImages(): { thumbnail: string; fullSize: string; zhLabel?: string; enLabel?: string; twLabel?: string }[] {
  return [
    { thumbnail: 'http://img.lyc.la/bangkok/1373_medium.jpg', fullSize: 'http://img.lyc.la/bangkok/1373.jpg', zhLabel: '曼谷', enLabel: 'Bangkok', twLabel: '曼谷' },
    { thumbnail: 'http://img.lyc.la/bangkok/1421_medium.jpg', fullSize: 'http://img.lyc.la/bangkok/1421.jpg', zhLabel: '曼谷', enLabel: 'Bangkok', twLabel: '曼谷' },
    { thumbnail: 'http://img.lyc.la/beijing/1553_medium.jpg', fullSize: 'http://img.lyc.la/beijing/1553.jpg', zhLabel: '北京', enLabel: 'Beijing', twLabel: '北京' },
    { thumbnail: 'http://img.lyc.la/beijing/1572_medium.jpg', fullSize: 'http://img.lyc.la/beijing/1572.jpg', zhLabel: '北京', enLabel: 'Beijing', twLabel: '北京' },
    { thumbnail: 'http://img.lyc.la/beijing/1581_medium.jpg', fullSize: 'http://img.lyc.la/beijing/1581.jpg', zhLabel: '北京', enLabel: 'Beijing', twLabel: '北京' },
    { thumbnail: 'http://img.lyc.la/beijing/1587_medium.jpg', fullSize: 'http://img.lyc.la/beijing/1587.jpg', zhLabel: '北京', enLabel: 'Beijing', twLabel: '北京' },
    { thumbnail: 'http://img.lyc.la/changsha/239_medium.jpg', fullSize: 'http://img.lyc.la/changsha/239.jpg', zhLabel: '长沙', enLabel: 'Changsha', twLabel: '長沙' },
    { thumbnail: 'http://img.lyc.la/chengdu/703_medium.jpg', fullSize: 'http://img.lyc.la/chengdu/703.jpg', zhLabel: '成都', enLabel: 'Chengdu', twLabel: '成都' },
    { thumbnail: 'http://img.lyc.la/chengdu/770_medium.jpg', fullSize: 'http://img.lyc.la/chengdu/770.jpg', zhLabel: '成都', enLabel: 'Chengdu', twLabel: '成都' },
    { thumbnail: 'http://img.lyc.la/easonchan/2218_medium.jpg', fullSize: 'http://img.lyc.la/easonchan/2218.jpg', zhLabel: '陈奕迅演唱会', enLabel: 'Eason Chan Concert', twLabel: '陳奕迅演唱會' },
    { thumbnail: 'http://img.lyc.la/fenghuang/212_medium.jpg', fullSize: 'http://img.lyc.la/fenghuang/212.jpg', zhLabel: '凤凰古城', enLabel: 'Fenghuang Ancient City', twLabel: '鳳凰古城' },
    { thumbnail: 'http://img.lyc.la/fenghuang/224_medium.jpg', fullSize: 'http://img.lyc.la/fenghuang/224.jpg', zhLabel: '凤凰古城', enLabel: 'Fenghuang Ancient City', twLabel: '鳳凰古城' },
    { thumbnail: 'http://img.lyc.la/fenghuang/225_medium.jpg', fullSize: 'http://img.lyc.la/fenghuang/225.jpg', zhLabel: '凤凰古城', enLabel: 'Fenghuang Ancient City', twLabel: '鳳凰古城' },
    { thumbnail: 'http://img.lyc.la/gem/4133_medium.jpg', fullSize: 'http://img.lyc.la/gem/4133.jpg', zhLabel: '邓紫棋演唱会', enLabel: 'G.E.M. Concert', twLabel: '鄧紫棋演唱會' },
    { thumbnail: 'http://img.lyc.la/guangzhou/380_medium.jpg', fullSize: 'http://img.lyc.la/guangzhou/380.jpg', zhLabel: '广州', enLabel: 'Guangzhou', twLabel: '廣州' },
    { thumbnail: 'http://img.lyc.la/guangzhou/393_medium.jpg', fullSize: 'http://img.lyc.la/guangzhou/393.jpg', zhLabel: '广州', enLabel: 'Guangzhou', twLabel: '廣州' },
    { thumbnail: 'http://img.lyc.la/guangzhou/415_medium.jpg', fullSize: 'http://img.lyc.la/guangzhou/415.jpg', zhLabel: '广州', enLabel: 'Guangzhou', twLabel: '廣州' },
    { thumbnail: 'http://img.lyc.la/guangzhou/419_medium.jpg', fullSize: 'http://img.lyc.la/guangzhou/419.jpg', zhLabel: '广州', enLabel: 'Guangzhou', twLabel: '廣州' },
    { thumbnail: 'http://img.lyc.la/huzhou/4024_medium.jpg', fullSize: 'http://img.lyc.la/huzhou/4024.jpg', zhLabel: '湖州', enLabel: 'Huzhou', twLabel: '湖州' },
    { thumbnail: 'http://img.lyc.la/jiuzhaigou/605_medium.jpg', fullSize: 'http://img.lyc.la/jiuzhaigou/605.jpg', zhLabel: '九寨沟', enLabel: 'Jiuzhaigou', twLabel: '九寨溝' },
    { thumbnail: 'http://img.lyc.la/jiuzhaigou/641_medium.jpg', fullSize: 'http://img.lyc.la/jiuzhaigou/641.jpg', zhLabel: '九寨沟', enLabel: 'Jiuzhaigou', twLabel: '九寨溝' },
    { thumbnail: 'http://img.lyc.la/pingtung/3303_medium.jpg', fullSize: 'http://img.lyc.la/pingtung/3303.jpg', zhLabel: '垦丁', enLabel: 'Kenting', twLabel: '墾丁' },
    { thumbnail: 'http://img.lyc.la/pingtung/3406_medium.jpg', fullSize: 'http://img.lyc.la/pingtung/3406.jpg', zhLabel: '垦丁', enLabel: 'Kenting', twLabel: '墾丁' },
    { thumbnail: 'http://img.lyc.la/pingtung/3538_medium.jpg', fullSize: 'http://img.lyc.la/pingtung/3538.jpg', zhLabel: '垦丁', enLabel: 'Kenting', twLabel: '墾丁' },
    { thumbnail: 'http://img.lyc.la/pingtung/3545_medium.jpg', fullSize: 'http://img.lyc.la/pingtung/3545.jpg', zhLabel: '垦丁', enLabel: 'Kenting', twLabel: '墾丁' },
    { thumbnail: 'http://img.lyc.la/lironghao/4150_medium.jpg', fullSize: 'http://img.lyc.la/lironghao/4150.jpg', zhLabel: '李荣浩演唱会', enLabel: 'Li Ronghao Concert', twLabel: '李榮浩演唱會' },
    { thumbnail: 'http://img.lyc.la/luoyang/137_medium.jpg', fullSize: 'http://img.lyc.la/luoyang/137.jpg', zhLabel: '洛阳', enLabel: 'Luoyang', twLabel: '洛陽' },
    { thumbnail: 'http://img.lyc.la/macau/250_medium.jpg', fullSize: 'http://img.lyc.la/macau/250.jpg', zhLabel: '澳门', enLabel: 'Macau', twLabel: '澳門' },
    { thumbnail: 'http://img.lyc.la/macau/275_medium.jpg', fullSize: 'http://img.lyc.la/macau/275.jpg', zhLabel: '澳门', enLabel: 'Macau', twLabel: '澳門' },
    { thumbnail: 'http://img.lyc.la/mayday/1899_medium.jpg', fullSize: 'http://img.lyc.la/mayday/1899.jpg', zhLabel: '五月天演唱会', enLabel: 'Mayday Concert', twLabel: '五月天演唱會' },
    { thumbnail: 'http://img.lyc.la/menyuan/1635_medium.jpg', fullSize: 'http://img.lyc.la/menyuan/1635.jpg', zhLabel: '门源', enLabel: 'Menyuan', twLabel: '門源' },
    { thumbnail: 'http://img.lyc.la/mianyang/603_medium.jpg', fullSize: 'http://img.lyc.la/mianyang/603.jpg', zhLabel: '绵阳', enLabel: 'Mianyang', twLabel: '綿陽' },
    { thumbnail: 'http://img.lyc.la/pattaya/1430_medium.jpg', fullSize: 'http://img.lyc.la/pattaya/1430.jpg', zhLabel: '芭堤雅', enLabel: 'Pattaya', twLabel: '芭堤雅' },
    { thumbnail: 'http://img.lyc.la/qinghailake/1617_medium.jpg', fullSize: 'http://img.lyc.la/qinghailake/1617.jpg', zhLabel: '青海湖', enLabel: 'Qinghai Lake', twLabel: '青海湖' },
    { thumbnail: 'http://img.lyc.la/qinghailake/1670_medium.jpg', fullSize: 'http://img.lyc.la/qinghailake/1670.jpg', zhLabel: '青海湖', enLabel: 'Qinghai Lake', twLabel: '青海湖' },
    { thumbnail: 'http://img.lyc.la/quanzhou/1816_medium.jpg', fullSize: 'http://img.lyc.la/quanzhou/1816.jpg', zhLabel: '泉州', enLabel: 'Quanzhou', twLabel: '泉州' },
    { thumbnail: 'http://img.lyc.la/quanzhou/22_medium.jpg', fullSize: 'http://img.lyc.la/quanzhou/22.jpg', zhLabel: '泉州', enLabel: 'Quanzhou', twLabel: '泉州' },
    { thumbnail: 'http://img.lyc.la/quanzhou/37_medium.jpg', fullSize: 'http://img.lyc.la/quanzhou/37.jpg', zhLabel: '泉州', enLabel: 'Quanzhou', twLabel: '泉州' },
    { thumbnail: 'http://img.lyc.la/richiejen/4041_medium.jpg', fullSize: 'http://img.lyc.la/richiejen/4041.jpg', zhLabel: '任贤齐演唱会', enLabel: 'Richie Jen Concert', twLabel: '任賢齊演唱會' },
    { thumbnail: 'http://img.lyc.la/shanghai/449_medium.jpg', fullSize: 'http://img.lyc.la/shanghai/449.jpg', zhLabel: '上海', enLabel: 'Shanghai', twLabel: '上海' },
    { thumbnail: 'http://img.lyc.la/shanghai/472_medium.jpg', fullSize: 'http://img.lyc.la/shanghai/472.jpg', zhLabel: '上海', enLabel: 'Shanghai', twLabel: '上海' },
    { thumbnail: 'http://img.lyc.la/shanghai/491_medium.jpg', fullSize: 'http://img.lyc.la/shanghai/491.jpg', zhLabel: '上海', enLabel: 'Shanghai', twLabel: '上海' },
    { thumbnail: 'http://img.lyc.la/shapotou/2467_medium.jpg', fullSize: 'http://img.lyc.la/shapotou/2467.jpg', zhLabel: '沙坡头', enLabel: 'Shapotou', twLabel: '沙坡頭' },
    { thumbnail: 'http://img.lyc.la/stefaniesun/4096_medium.jpg', fullSize: 'http://img.lyc.la/stefaniesun/4096.jpg', zhLabel: '孙燕姿演唱会', enLabel: 'Stefanie Sun Concert', twLabel: '孫燕姿演唱會' },
    { thumbnail: 'http://img.lyc.la/stevechou/4702_medium.jpg', fullSize: 'http://img.lyc.la/stevechou/4702.jpg', zhLabel: '周传雄演唱会', enLabel: 'Steve Chou Concert', twLabel: '周傳雄演唱會' },
    { thumbnail: 'http://img.lyc.la/stevechou/4708_medium.jpg', fullSize: 'http://img.lyc.la/stevechou/4708.jpg', zhLabel: '周传雄演唱会', enLabel: 'Steve Chou Concert', twLabel: '周傳雄演唱會' },
    { thumbnail: 'http://img.lyc.la/tainan/3030_medium.jpg', fullSize: 'http://img.lyc.la/tainan/3030.jpg', zhLabel: '台南', enLabel: 'Tainan', twLabel: '臺南' },
    { thumbnail: 'http://img.lyc.la/tainan/3093_medium.jpg', fullSize: 'http://img.lyc.la/tainan/3093.jpg', zhLabel: '台南', enLabel: 'Tainan', twLabel: '臺南' },
    { thumbnail: 'http://img.lyc.la/newtaipei/2560_medium.jpg', fullSize: 'http://img.lyc.la/newtaipei/2560.jpg', zhLabel: '新北', enLabel: 'Taipei', twLabel: '新北' },
    { thumbnail: 'http://img.lyc.la/taipei/2600_medium.jpg', fullSize: 'http://img.lyc.la/taipei/2600.jpg', zhLabel: '台北', enLabel: 'Taipei', twLabel: '臺北' },
    { thumbnail: 'http://img.lyc.la/taitung/3594_medium.jpg', fullSize: 'http://img.lyc.la/taitung/3594.jpg', zhLabel: '台东', enLabel: 'Taitung', twLabel: '臺東' },
    { thumbnail: 'http://img.lyc.la/tibet/1196_medium.jpg', fullSize: 'http://img.lyc.la/tibet/1196.jpg', zhLabel: '西藏', enLabel: 'Tibet', twLabel: '西藏' },
    { thumbnail: 'http://img.lyc.la/tibet/1220_medium.jpg', fullSize: 'http://img.lyc.la/tibet/1220.jpg', zhLabel: '西藏', enLabel: 'Tibet', twLabel: '西藏' },
    { thumbnail: 'http://img.lyc.la/tibet/1229_medium.jpg', fullSize: 'http://img.lyc.la/tibet/1229.jpg', zhLabel: '西藏', enLabel: 'Tibet', twLabel: '西藏' },
    { thumbnail: 'http://img.lyc.la/tibet/1266_medium.jpg', fullSize: 'http://img.lyc.la/tibet/1266.jpg', zhLabel: '西藏', enLabel: 'Tibet', twLabel: '西藏' },
    { thumbnail: 'http://img.lyc.la/tibet/1296_medium.jpg', fullSize: 'http://img.lyc.la/tibet/1296.jpg', zhLabel: '西藏', enLabel: 'Tibet', twLabel: '西藏' },
    { thumbnail: 'http://img.lyc.la/wubai/4204_medium.jpg', fullSize: 'http://img.lyc.la/wubai/4204.jpg', zhLabel: '伍佰演唱会', enLabel: 'Wu Bai Concert', twLabel: '伍佰演唱會' },
    { thumbnail: 'http://img.lyc.la/wubai/4211_medium.jpg', fullSize: 'http://img.lyc.la/wubai/4211.jpg', zhLabel: '伍佰演唱会', enLabel: 'Wu Bai Concert', twLabel: '伍佰演唱會' },
    { thumbnail: 'http://img.lyc.la/wutai/573_medium.jpg', fullSize: 'http://img.lyc.la/wutai/573.jpg', zhLabel: '五台山', enLabel: 'Wutai Mountain', twLabel: '五臺山' },
    { thumbnail: 'http://img.lyc.la/xinjiang/31_medium.jpg', fullSize: 'http://img.lyc.la/xinjiang/31.jpg', zhLabel: '新疆', enLabel: 'Xinjiang', twLabel: '新疆' },
    { thumbnail: 'http://img.lyc.la/xitang/97_medium.jpg', fullSize: 'http://img.lyc.la/xitang/97.jpg', zhLabel: '西塘', enLabel: 'Xitang', twLabel: '西塘' },
    { thumbnail: 'http://img.lyc.la/xuankong/575_medium.jpg', fullSize: 'http://img.lyc.la/xuankong/575.jpg', zhLabel: '悬空寺', enLabel: 'Hanging Temple', twLabel: '懸空寺' },
  ];
}

export const SOCIAL_IMAGES = [
  { src: 'http://img.lyc.la/tibet/1296.jpg', zhLabel: '西藏 . 拉萨', enLabel: 'Tibet . Lhasa', twLabel: '西藏 . 拉薩' },
  { src: 'http://img.lyc.la/tianjin/4001.jpg', zhLabel: '天津', enLabel: 'Tianjin', twLabel: '天津' },
  { src: 'http://img.lyc.la/newtaipei/2560.jpg', zhLabel: '臺灣 . 臺北', enLabel: 'Taiwan . Taipei', twLabel: '臺灣 . 臺北' },
  { src: 'http://img.lyc.la/pingtung/3879-1.jpg', zhLabel: '臺灣 . 墾丁', enLabel: 'Taiwan . Kenting', twLabel: '臺灣 . 墾丁' },
  { src: 'http://img.lyc.la/seoul/1082.jpg', zhLabel: '韩国 . 首尔', enLabel: 'Korea . Seoul', twLabel: '韓國 . 首爾' },
  { src: 'http://img.lyc.la/bangkok/1409.jpg', zhLabel: '泰国 . 曼谷', enLabel: 'Thailand . Bangkok', twLabel: '泰國 . 曼谷' },
  { src: 'http://img.lyc.la/shapotou/2421-1.jpg', zhLabel: '宁夏 . 中卫', enLabel: 'Ningxia . Zhongwei', twLabel: '寧夏 . 中衛' },
  { src: 'http://img.lyc.la/huzhou/4000.jpg', zhLabel: '浙江 . 湖州', enLabel: 'Zhejiang . Huzhou', twLabel: '浙江 . 湖州' },
  { src: 'http://img.lyc.la/beijing/1572.jpg', zhLabel: '北京 . 天安门', enLabel: 'Beijing . Tiananmen Square', twLabel: '北京 . 天安門' }
];

export const SOCIAL_LINKS = [
  { icon: 'fas fa-globe', url: 'http://www.lyc.la', zhLabel: 'lyc.la', enLabel: 'lyc.la', twLabel: 'lyc.la' },
  { icon: 'fas fa-heartbeat', url: 'http://hi.lyc.la', zhLabel: 'hi lyc', enLabel: 'hi lyc', twLabel: 'hi lyc' },
  { icon: 'fas fa-blog', url: 'http://b.lyc.la', zhLabel: '博客 lyc', enLabel: 'blog lyc', twLabel: '博客 lyc' },
  { icon: 'fas fa-music', url: 'http://ilive.lyc.la', zhLabel: '演唱会 lyc', enLabel: 'ilive lyc', twLabel: '演唱會 lyc' },
  { icon: 'fa-brands fa-github', url: 'https://github.com/layicr', zhLabel: 'Github', enLabel: 'Github', twLabel: 'Github' },
  { icon: 'fa-brands fa-weibo', url: 'http://weibo.com/layicr', zhLabel: '微博', enLabel: 'Weibo', twLabel: '微博' },
  { icon: 'fa-brands fa-weixin', url: 'https://mp.weixin.qq.com/s/S1sq45LC_iQuCLYxzoaRkw', zhLabel: '微信', enLabel: 'Weixin', twLabel: '微信' },
  { icon: 'fab fa-tiktok', url: 'https://v.douyin.com/5nAiAZQoUXw/', zhLabel: '抖音', enLabel: 'TikTok', twLabel: '抖音' },
  { icon: 'fa fa-play-circle', url: 'https://space.bilibili.com/29825132', zhLabel: 'Bilibili', enLabel: 'Bilibili', twLabel: 'Bilibili' },
  { icon: 'fab fa-twitter', url: 'http://twitter.com/layicr', zhLabel: 'Twitter', enLabel: 'Twitter', twLabel: 'Twitter' },
  { icon: 'fab fa-instagram', url: 'http://www.instagram.com/ilayicr', zhLabel: 'Instagram', enLabel: 'Instagram', twLabel: 'Instagram' },
  { icon: 'fab fa-facebook', url: 'http://www.facebook.com/layicr', zhLabel: 'Facebook', enLabel: 'Facebook', twLabel: 'Facebook' },
  { icon: 'fab fa-youtube', url: 'http://youtube.com/@lyc9530', zhLabel: 'YouTube', enLabel: 'YouTube', twLabel: 'YouTube' }
];
